plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.4.10'
    id 'org.jetbrains.kotlin.plugin.spring' version '2.4.10'
    id 'org.springframework.boot' version '3.5.16'
    id 'jacoco'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-actuator:3.5.16")
    implementation('jakarta.validation:jakarta.validation-api:3.1.1')
    implementation("org.springframework.boot:spring-boot-starter:3.5.16") {
        exclude group: 'org.yaml', module: 'snakeyaml'
    }
    implementation("org.springframework.boot:spring-boot-starter-web:3.5.16")
    implementation("org.springframework.boot:spring-boot-starter-security:3.5.16")
    implementation("org.springframework.boot:spring-boot-starter-validation:3.5.16")
    implementation("org.springframework.boot:spring-boot-starter-oauth2-client:3.5.16")
    implementation("org.springframework.boot:spring-boot-starter-oauth2-resource-server:3.5.16")
    implementation('com.nimbusds:nimbus-jose-jwt:10.9.1')
    implementation('org.jetbrains.kotlin:kotlin-reflect')
    implementation('org.jetbrains.kotlin:kotlin-stdlib-jdk8')

  
    testImplementation('io.specmatic:junit5-support:2.52.0')
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.5.16")
    testImplementation("org.springframework.security:spring-security-test:6.5.11")
    testImplementation("org.mockito.kotlin:mockito-kotlin:5.4.0")
    testImplementation("io.specmatic.enterprise:executable:$specmaticEnterpriseVersion")
    testImplementation('org.jetbrains.kotlin:kotlin-test-junit5')
    testImplementation('org.testcontainers:junit-jupiter:1.21.4')
}

tasks.withType(Test) {
    useJUnitPlatform()
}

jacoco {
    toolVersion = '0.8.15'
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    '**/DB.*',
                    '**/APIKeyAuthFilter.*'
            ])
        }))
    }
}
